export const GENERATED_PATHS = [
  "README.md", "reference/tools.md", "reference/workflow.md",
  "integrations/microsoft-mcp/mcptools.json", "plugin.json",
  ".codex-plugin/plugin.json", ".cursor-plugin/plugin.json",
  "gemini-extension.json", "integrations/microsoft-mcp/manifest.template.json",
];

/** A bot may merge only the exact generated bytes validated in this run. */
export function validateSyncPullRequest(pr, files, snapshot, blobs, headSha, mainSha) {
  if (pr.state !== "open" || pr.user?.login !== "github-actions[bot]"
      || pr.base?.ref !== "main" || pr.head?.ref !== "automation/sync-mcp-surface"
      || pr.head?.repo?.full_name !== pr.base?.repo?.full_name
      || pr.head?.sha !== headSha || pr.base?.sha !== snapshot.baseSha
      || mainSha !== snapshot.baseSha) {
    throw new Error("Sync PR identity, revision, or base changed; refusing automatic merge");
  }
  if (!files.length || files.length !== pr.changed_files) {
    throw new Error("Sync PR file inventory is empty or incomplete");
  }
  for (const file of files) {
    if (!GENERATED_PATHS.includes(file.filename) || file.status === "removed"
        || file.previous_filename || !snapshot.blobs[file.filename]
        || blobs[file.filename] !== snapshot.blobs[file.filename]) {
      throw new Error(`Sync PR contains an unvalidated change: ${file.filename}`);
    }
  }
}
