import assert from "node:assert/strict";
import test from "node:test";
import { validateSyncPullRequest } from "../lib/sync-publish.mjs";
import { workflowReference } from "../lib/workflow-reference.mjs";

function fixture() {
  return {
    pr: { state: "open", user: { login: "github-actions[bot]" }, changed_files: 1,
      base: { ref: "main", sha: "base", repo: { full_name: "minds-ai-co/minds-mcp" } },
      head: { ref: "automation/sync-mcp-surface", sha: "head", repo: { full_name: "minds-ai-co/minds-mcp" } } },
    files: [{ filename: "reference/workflow.md", status: "modified" }],
    snapshot: { baseSha: "base", blobs: { "reference/workflow.md": "validated-blob" } },
    blobs: { "reference/workflow.md": "validated-blob" },
    mainSha: "base",
  };
}
function verify(data) {
  return validateSyncPullRequest(data.pr, data.files, data.snapshot, data.blobs, "head", data.mainSha);
}

test("permits only validated bot-generated documentation", () => assert.doesNotThrow(() => verify(fixture())));
for (const [name, change] of [
  ["a human PR", data => { data.pr.user.login = "human"; }],
  ["a foreign branch", data => { data.pr.head.ref = "feature/unrelated"; }],
  ["a fork", data => { data.pr.head.repo.full_name = "other/minds-mcp"; }],
  ["a changed revision", data => { data.pr.head.sha = "changed"; }],
  ["an advanced main", data => { data.mainSha = "new-base"; }],
  ["a changed base", data => { data.pr.base.sha = "new-base"; }],
  ["unexpected workflow changes", data => { data.files[0].filename = ".github/workflows/sync-mcp-surface.yml"; }],
  ["altered generated bytes", data => { data.blobs["reference/workflow.md"] = "edited-blob"; }],
  ["a deletion", data => { data.files[0].status = "removed"; }],
  ["a rename", data => { data.files[0].previous_filename = "other.md"; }],
  ["incomplete file pagination", data => { data.pr.changed_files = 2; }],
]) {
  test(`automatic merge refuses ${name}`, () => {
    const data = fixture();
    change(data);
    assert.throws(() => verify(data));
  });
}

test("behavior guidance follows arbitrary new tools and schema changes", () => {
  const render = format => workflowReference([{ name: "new_operation", title: "New operation",
    description: "Runs a newly documented operation. Preserve the returned retry key.",
    inputSchema: { required: ["format"], properties: {
      format: { type: "string", enum: [format], description: "Export format.", default: format },
    } },
  }]);
  assert.match(render("pdf"), /returned retry key/);
  assert.match(render("pdf"), /\| `format` \| Yes \| "pdf"/);
  assert.match(render("csv"), /\| `format` \| Yes \| "csv"/);
  assert.doesNotMatch(render("csv"), /"pdf"/);
});
